[package]
name = "phpast"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3.26", features = ["color"]  }
trunk_lexer = { path = "../trunk_lexer" }
trunk_parser = { path = "../trunk_parser" }
