[package]
name = "phpc"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3.26", features = ["color"]  }
trunk_parser = { path = "../trunk_parser" }
trunk_lexer = { path = "../trunk_lexer" }
rust-format = "0.3.4"