name: third-party

on:
  push:
    branches: [main]
  pull_request:

jobs:
  third-party-tests:
    name: third-party
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 'stable'
        os:
          - 'ubuntu-latest'
        target:
          - 'psl'
          - 'php-parser'
          - 'symfony'
          - 'laravel'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: install just
        run: |
          cargo install just

      - name: test ${{ matrix.target }}
        run: just test-${{ matrix.target }}
